### ISSUE TITLE
File <auw_signed.pdf> to write to is not in binary mode.

### ISSUE THREAD

**Issue by altela** [yourcelf/signpdf#5]
Hi, first of all i would like to say thanks for making this script. 
After i tried this, it's shows some error with this message :

```
UserWarning: File <auw_signed.pdf> to write to is not in binary mode. It may not be written to correctly. [pdf.py:453]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/signpdf", line 33, in <module>
    sys.exit(load_entry_point('signpdf==0.0.3', 'console_scripts', 'signpdf')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/signpdf.py", line 72, in main
    sign_pdf(parser.parse_args())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/signpdf.py", line 63, in sign_pdf
    writer.write(fh)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PyPDF2/pdf.py", line 487, in write
    stream.write(self._header + b_("\n"))
TypeError: write() argument must be str, not bytes
```
I also read opened issue number #2 . After that, i checked signpdf.py but it seems like nothing is wrong.
I'm using python3.9, what could be the main cause of this?

**Comment by Agent-Hellboy** [comment]
I told him about this last year. check this out #4 
what you can do is uninstall the package and install it using
`pip install git+https://github.com/yourcelf/signpdf.git`

**Comment by altela** [comment]
hi, thank you for replying. i'll later close this issue then.
